Add capitalize
alisavch/strings pull request #2
Opened 2021-05-18 13:01 UTC by alisavch

new function capitalize released

2021-05-19 13:51 UTC, papahmsolo requested changes
Looks good

Let's rename the module to match the repo location

2021-05-19 13:51 UTC, papahmsolo commented on strings.go
> +}
No need to declare a variable here

2021-05-19 13:51 UTC, papahmsolo commented on strings_test.go
> +	}{
can we use short variable declaration (same for reverse)?

2021-05-19 13:51 UTC, papahmsolo commented on strings_test.go
> +		{"Olá", "OLÁ"},
This basically test the same thing, try to test some different properties, say numbers instead

2021-05-19 16:05 UTC, alisavch commented on strings.go
> +}
ok thanks

2021-05-19 16:08 UTC, alisavch commented on strings_test.go
> +	}{
yeah, of course

2021-05-20 09:54 UTC, papahmsolo approved these changes
lgtm 👍

2021-05-20 09:54 UTC, merged